const { contextBridge, ipcRenderer } = require('electron');

const on = (channel) => (cb) => ipcRenderer.on(channel, (_e, ...args) => cb(...args));

contextBridge.exposeInMainWorld('api', {
  getSettings: () => ipcRenderer.invoke('get-settings'),
  getState: () => ipcRenderer.invoke('get-state'),
  setSettings: (patch) => ipcRenderer.send('set-settings', patch),
  resetLook: () => ipcRenderer.send('reset-look'),
  saveProfile: (name) => ipcRenderer.send('save-profile', name),
  loadProfile: (name) => ipcRenderer.send('load-profile', name),
  deleteProfile: (name) => ipcRenderer.send('delete-profile', name),
  exportSettings: () => ipcRenderer.invoke('export-settings'),
  importSettings: () => ipcRenderer.invoke('import-settings'),
  dismissWhatsNew: () => ipcRenderer.send('dismiss-whats-new'),
  installUpdate: () => ipcRenderer.send('install-update'),
  downloadUpdate: () => ipcRenderer.send('download-update'),
  testLiveAlert: () => ipcRenderer.send('test-live-alert'),
  toggleAlertEdit: () => ipcRenderer.send('toggle-alert-edit'),
  alertReady: () => ipcRenderer.send('alert-ready'),
  alertShow: () => ipcRenderer.send('alert-show'),
  alertIdle: () => ipcRenderer.send('alert-idle'),
  pauseShortcuts: () => ipcRenderer.send('pause-shortcuts'),
  resumeShortcuts: () => ipcRenderer.send('resume-shortcuts'),
  openRepo: () => ipcRenderer.send('open-repo'),
  toggleEdit: () => ipcRenderer.send('toggle-edit'),
  toggleVisible: () => ipcRenderer.send('toggle-visible'),
  toggleTest: () => ipcRenderer.send('toggle-test'),
  setPosition: (pos) => ipcRenderer.send('set-position', pos),
  setSize: (w, h) => ipcRenderer.send('set-size', w, h),
  resizeStart: () => ipcRenderer.send('resize-start'),
  resizeMove: (dx, dy) => ipcRenderer.send('resize-move', dx, dy),
  resizeEnd: () => ipcRenderer.send('resize-end'),
  onSettings: on('settings'),
  onEditMode: on('edit-mode'),
  onState: on('state'),
  onTestMode: on('test-mode'),
  onReconnect: on('reconnect'),
  onToast: on('toast'),
  onLiveAlert: on('live-alert'),
  onAlertEdit: on('alert-edit'),
});
